CREATE ROLE emr_user WITH LOGIN PASSWORD 'emr_password';
CREATE DATABASE emr_db OWNER emr_user;
GRANT ALL PRIVILEGES ON DATABASE emr_db TO emr_user;
\c emr_db
GRANT ALL ON SCHEMA public TO emr_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO emr_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO emr_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO emr_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO emr_user;
