"""add_medications_table

Revision ID: 93fea7a35eb8
Revises: enhanced_report_001
Create Date: 2025-10-18 15:30:34.446416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93fea7a35eb8'
down_revision: Union[str, None] = 'enhanced_report_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('common_dosages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=False)
    op.create_index('ix_medications_name_lower', 'medications', ['name'], unique=False, postgresql_ops={'name': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medications_name_lower', table_name='medications')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
