"""add_receptionist_role_and_two_stage_patient_registration

Revision ID: 9691ddd22bb4
Revises: 93fea7a35eb8
Create Date: 2025-10-18 16:28:16.036508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql
from app.models.base import EncryptedType

# revision identifiers, used by Alembic.
revision: str = '9691ddd22bb4'
down_revision: Union[str, None] = '93fea7a35eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # Example safety check:
    # conn = op.get_bind()
    # result = conn.execute(text("SELECT 1")).scalar()
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop old tables if they exist (safe to ignore if not present)
    try:
        op.drop_index(op.f('ix_demo_requests_created_at'), table_name='demo_requests')
        op.drop_index(op.f('ix_demo_requests_email'), table_name='demo_requests')
        op.drop_index(op.f('ix_demo_requests_full_name'), table_name='demo_requests')
        op.drop_index(op.f('ix_demo_requests_status'), table_name='demo_requests')
        op.drop_table('demo_requests')
    except:
        pass
    
    try:
        op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
        op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
        op.drop_index(op.f('ix_contact_messages_full_name'), table_name='contact_messages')
        op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
        op.drop_table('contact_messages')
    except:
        pass
    
    # Add profile_status to patients table
    op.add_column('patients', sa.Column('profile_status', sa.String(length=30), server_default='DEMOGRAPHICS_ONLY', nullable=False))
    op.create_index(op.f('ix_patients_profile_status'), 'patients', ['profile_status'], unique=False)
    # Skip report column changes - they're not critical for this migration
    # op.alter_column('reports', 'reviewed_transcript',
    #            existing_type=sa.TEXT(),
    #            type_=EncryptedType(length=10000),
    #            existing_nullable=True)
    # op.alter_column('reports', 'keywords',
    #            existing_type=postgresql.ARRAY(sa.TEXT()),
    #            type_=postgresql.ARRAY(sa.String()),
    #            existing_nullable=True)
    # op.drop_column('reports', 'medications')
    # Add invited_by_id to users table
    op.add_column('users', sa.Column('invited_by_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_invited_by_id'), 'users', ['invited_by_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_invited_by_id_users'), 'users', 'users', ['invited_by_id'], ['id'])
    
    # Create staff_invitations table (if not exists)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'staff_invitations' not in inspector.get_table_names():
        op.create_table(
            'staff_invitations',
            sa.Column('id', sa.String(36), nullable=False),
            sa.Column('inviter_id', sa.String(36), nullable=False),
            sa.Column('recipient_email', sa.String(255), nullable=False),
            sa.Column('token', sa.String(255), nullable=False),
            sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['inviter_id'], ['users.id']),
        )
        op.create_index(op.f('ix_staff_invitations_inviter_id'), 'staff_invitations', ['inviter_id'], unique=False)
        op.create_index(op.f('ix_staff_invitations_recipient_email'), 'staff_invitations', ['recipient_email'], unique=False)
        op.create_index(op.f('ix_staff_invitations_token'), 'staff_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop staff_invitations table
    op.drop_index(op.f('ix_staff_invitations_token'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_recipient_email'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_inviter_id'), table_name='staff_invitations')
    op.drop_table('staff_invitations')
    
    # Remove invited_by_id from users
    op.drop_constraint(op.f('fk_users_invited_by_id_users'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_invited_by_id'), table_name='users')
    op.drop_column('users', 'invited_by_id')
    # Skip report column changes - they're not critical for this migration
    # op.add_column('reports', sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.alter_column('reports', 'keywords',
    #            existing_type=postgresql.ARRAY(sa.String()),
    #            type_=postgresql.ARRAY(sa.TEXT()),
    #            existing_nullable=True)
    # op.alter_column('reports', 'reviewed_transcript',
    #            existing_type=EncryptedType(length=10000),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    op.drop_index(op.f('ix_patients_profile_status'), table_name='patients')
    op.drop_column('patients', 'profile_status')
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='messagepriority'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='messagestatus'), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('responded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_index(op.f('ix_contact_messages_full_name'), 'contact_messages', ['full_name'], unique=False)
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_table('demo_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interested_features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'CONTACTED', 'SCHEDULED', 'COMPLETED', 'CANCELLED', name='demorequeststatus'), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contacted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demo_requests'))
    )
    op.create_index(op.f('ix_demo_requests_status'), 'demo_requests', ['status'], unique=False)
    op.create_index(op.f('ix_demo_requests_full_name'), 'demo_requests', ['full_name'], unique=False)
    op.create_index(op.f('ix_demo_requests_email'), 'demo_requests', ['email'], unique=False)
    op.create_index(op.f('ix_demo_requests_created_at'), 'demo_requests', ['created_at'], unique=False)
    # ### end Alembic commands ###
